/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.test;

import PoS.PoS;
import PoS.classes.Employee;
import javax.swing.table.DefaultTableModel;
import javax.swing.ListSelectionModel;
import java.awt.Component;

/**
 *
 * @author Dustin Gritman
 */
public class EmployeePanel extends javax.swing.JPanel {
    private final PoS pos;
    
    /**
     * Creates new form TestEmployeePanel
     * @param pos A PoS object from the main program.
     */
    public EmployeePanel(PoS pos) {
        initComponents();
        this.pos = pos;
        
        employeeTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        updatEmployeeTableData();
        
        cuAccessLevel.addItem("User");
        cuAccessLevel.addItem("Admin");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgEditEmployee = new javax.swing.JDialog();
        eelblFirstName = new javax.swing.JLabel();
        eeFirstName = new javax.swing.JTextField();
        eelblLastName = new javax.swing.JLabel();
        eeLastName = new javax.swing.JTextField();
        eelblTitle = new javax.swing.JLabel();
        eeTitle = new javax.swing.JTextField();
        eelblPhone = new javax.swing.JLabel();
        eePhone = new javax.swing.JTextField();
        eelblState = new javax.swing.JLabel();
        eeState = new javax.swing.JTextField();
        eelblCity = new javax.swing.JLabel();
        eeCity = new javax.swing.JTextField();
        eelblStreet = new javax.swing.JLabel();
        eeStreet = new javax.swing.JTextField();
        eelblZip = new javax.swing.JLabel();
        eeZip = new javax.swing.JTextField();
        btneeSubmit = new javax.swing.JButton();
        eelblEmail = new javax.swing.JLabel();
        eeEmail = new javax.swing.JTextField();
        dlgCreateUser = new javax.swing.JDialog();
        culblUsername = new javax.swing.JLabel();
        cuUsername = new javax.swing.JTextField();
        culblPassword = new javax.swing.JLabel();
        cuPassword = new javax.swing.JPasswordField();
        culblEmployeeID = new javax.swing.JLabel();
        cuEmployeeID = new javax.swing.JTextField();
        culblAccess = new javax.swing.JLabel();
        cuAccessLevel = new javax.swing.JComboBox<>();
        btncuSubmit = new javax.swing.JButton();
        scrollPaneTable = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        btnCreateEmployee = new javax.swing.JButton();
        btnEditEmployee = new javax.swing.JButton();
        btnDeleteEmployee = new javax.swing.JButton();
        btnCreateUser = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        dlgEditEmployee.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgEditEmployee.setTitle("Edit User");
        dlgEditEmployee.setAlwaysOnTop(true);
        dlgEditEmployee.setResizable(false);
        dlgEditEmployee.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                dlgEditEmployeeWindowClosed(evt);
            }
        });

        eelblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eelblFirstName.setText("First Name");

        eelblLastName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eelblLastName.setText("Last Name");

        eelblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eelblTitle.setText("Title");

        eelblPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eelblPhone.setText("Phone");

        eelblState.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eelblState.setText("State");

        eelblCity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eelblCity.setText("City");

        eelblStreet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eelblStreet.setText("Street");

        eelblZip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eelblZip.setText("Zip");

        btneeSubmit.setText("Submit");
        btneeSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneeSubmitActionPerformed(evt);
            }
        });

        eelblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eelblEmail.setText("Email");

        javax.swing.GroupLayout dlgEditEmployeeLayout = new javax.swing.GroupLayout(dlgEditEmployee.getContentPane());
        dlgEditEmployee.getContentPane().setLayout(dlgEditEmployeeLayout);
        dlgEditEmployeeLayout.setHorizontalGroup(
            dlgEditEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgEditEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgEditEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btneeSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dlgEditEmployeeLayout.createSequentialGroup()
                        .addGroup(dlgEditEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eeFirstName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eelblFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(eelblStreet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eeStreet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dlgEditEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dlgEditEmployeeLayout.createSequentialGroup()
                                .addComponent(eelblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eelblState, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eelblZip, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dlgEditEmployeeLayout.createSequentialGroup()
                                .addComponent(eeLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eeEmail))
                            .addGroup(dlgEditEmployeeLayout.createSequentialGroup()
                                .addComponent(eelblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eelblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eelblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eelblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dlgEditEmployeeLayout.createSequentialGroup()
                                .addComponent(eeCity, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eeState, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eeZip, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        dlgEditEmployeeLayout.setVerticalGroup(
            dlgEditEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgEditEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgEditEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eelblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dlgEditEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eelblFirstName)
                        .addComponent(eelblLastName)
                        .addComponent(eelblPhone)
                        .addComponent(eelblEmail)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgEditEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eeLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eeFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgEditEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eelblState)
                    .addGroup(dlgEditEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eelblCity)
                        .addComponent(eelblStreet)
                        .addComponent(eelblZip)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgEditEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eeCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eeStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eeZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eeState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btneeSubmit)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        dlgCreateUser.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgCreateUser.setTitle("Create User");
        dlgCreateUser.setAlwaysOnTop(true);
        dlgCreateUser.setMinimumSize(new java.awt.Dimension(205, 175));
        dlgCreateUser.setName("dlgCreateUser"); // NOI18N
        dlgCreateUser.setResizable(false);
        dlgCreateUser.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                dlgCreateUserWindowClosed(evt);
            }
        });

        culblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        culblUsername.setText("Username");
        culblUsername.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        culblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        culblPassword.setText("Password");
        culblPassword.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        culblEmployeeID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        culblEmployeeID.setText("Employee ID");

        culblAccess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        culblAccess.setText("Access Level");

        btncuSubmit.setText("Submit");
        btncuSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncuSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgCreateUserLayout = new javax.swing.GroupLayout(dlgCreateUser.getContentPane());
        dlgCreateUser.getContentPane().setLayout(dlgCreateUserLayout);
        dlgCreateUserLayout.setHorizontalGroup(
            dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgCreateUserLayout.createSequentialGroup()
                .addGroup(dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgCreateUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dlgCreateUserLayout.createSequentialGroup()
                                .addComponent(culblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 6, Short.MAX_VALUE))
                            .addComponent(cuEmployeeID)
                            .addComponent(culblEmployeeID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cuUsername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cuPassword)
                            .addComponent(culblAccess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(culblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cuAccessLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(dlgCreateUserLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btncuSubmit)))
                .addGap(31, 31, 31))
        );
        dlgCreateUserLayout.setVerticalGroup(
            dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgCreateUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(culblUsername)
                    .addComponent(culblPassword))
                .addGap(3, 3, 3)
                .addGroup(dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(culblEmployeeID)
                    .addComponent(culblAccess))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuAccessLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncuSubmit)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee_ID", "First Name", "First Name", "Title", "Phone", "Email", "StartDate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employeeTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeTable.getTableHeader().setReorderingAllowed(false);
        scrollPaneTable.setViewportView(employeeTable);
        employeeTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (employeeTable.getColumnModel().getColumnCount() > 0) {
            employeeTable.getColumnModel().getColumn(0).setResizable(false);
            employeeTable.getColumnModel().getColumn(1).setResizable(false);
            employeeTable.getColumnModel().getColumn(2).setResizable(false);
            employeeTable.getColumnModel().getColumn(3).setResizable(false);
            employeeTable.getColumnModel().getColumn(4).setResizable(false);
            employeeTable.getColumnModel().getColumn(5).setResizable(false);
            employeeTable.getColumnModel().getColumn(6).setResizable(false);
        }

        btnCreateEmployee.setText("Create Employee");
        btnCreateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEmployeeActionPerformed(evt);
            }
        });

        btnEditEmployee.setText("Edit Employee");
        btnEditEmployee.setToolTipText("");
        btnEditEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditEmployeeActionPerformed(evt);
            }
        });

        btnDeleteEmployee.setText("Delete Employee");
        btnDeleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEmployeeActionPerformed(evt);
            }
        });

        btnCreateUser.setText("Create User");
        btnCreateUser.setToolTipText("");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });

        btnBack.setText("Back");

        btnExit.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBack, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateEmployee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteEmployee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditEmployee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateEmployee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditEmployeeActionPerformed
        int selectedRow = employeeTable.getSelectedRow();
        if (selectedRow < 0)
            return;
        
        DefaultTableModel model = (DefaultTableModel)employeeTable.getModel();
        String firstName = (String)model.getValueAt(selectedRow, 0);
        String lastName = (String)model.getValueAt(selectedRow, 1);
        String title = (String)model.getValueAt(selectedRow, 2);
        String phone = (String)model.getValueAt(selectedRow, 3);
        String email = (String)model.getValueAt(selectedRow, 4);
        
        eeFirstName.setText(firstName);
        eeLastName.setText(lastName);
        eeTitle.setText(title);
        eePhone.setText(phone);
        eeEmail.setText(email);
        
        dlgEditEmployee.setSize(dlgEditEmployee.getPreferredSize());
        disableMainPanel();
        dlgEditEmployee.setVisible(true);
    }//GEN-LAST:event_btnEditEmployeeActionPerformed

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        int selectedRow = employeeTable.getSelectedRow();
        if (selectedRow < 0)
            return;
        
        DefaultTableModel model = (DefaultTableModel)employeeTable.getModel();
        int employeeid = (int)model.getValueAt(selectedRow, 0);
        cuEmployeeID.setText(String.valueOf(employeeid));
        
        dlgCreateUser.setSize(dlgCreateUser.getPreferredSize());
        disableMainPanel();
        dlgCreateUser.setVisible(true);
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btncuSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncuSubmitActionPerformed
        int employeeid = Integer.valueOf(cuEmployeeID.getText());
        String username = cuUsername.getText();
        char[] password = cuPassword.getPassword();
        short accesslevel = 1;
        if (cuAccessLevel.getSelectedItem() == "Admin")
            accesslevel = 5;
        
        pos.users.create(employeeid, username, password, accesslevel);
        dlgCreateUser.dispose();
    }//GEN-LAST:event_btncuSubmitActionPerformed

    private void dlgCreateUserWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlgCreateUserWindowClosed
        cuUsername.setText("");
        cuEmployeeID.setText("");
        cuPassword.setText("");
        cuAccessLevel.setSelectedIndex(0);
        enableMainPanel();
    }//GEN-LAST:event_dlgCreateUserWindowClosed

    private void btneeSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneeSubmitActionPerformed
        // ADD CODE FOR EDITING EMPLOYEE
    }//GEN-LAST:event_btneeSubmitActionPerformed

    private void dlgEditEmployeeWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlgEditEmployeeWindowClosed
        enableMainPanel();
    }//GEN-LAST:event_dlgEditEmployeeWindowClosed

    private void btnDeleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEmployeeActionPerformed
        System.out.println("DELETE Employee!");
    }//GEN-LAST:event_btnDeleteEmployeeActionPerformed

    private void btnCreateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateEmployeeActionPerformed

    private void disableMainPanel() {
        Component[] components = getComponents();
        for (Component component : components)
            component.setEnabled(false);
        employeeTable.setEnabled(false);
    }
    
    private void enableMainPanel() {
        Component[] components = getComponents();
        for (Component component : components)
            component.setEnabled(true);
        employeeTable.setEnabled(true);
    }
    
    private void updatEmployeeTableData() {
        DefaultTableModel model = (DefaultTableModel)employeeTable.getModel();
        model.setRowCount(0);
        Employee[] employeeList = pos.employees.loadAll();
        for (Employee employee : employeeList)
            model.addRow(new Object[]{employee.getID(), employee.getFirstName()
                    , employee.getLastName(), employee.getTitle()
                    , employee.getPhone(), employee.getEmail()}
            );
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateEmployee;
    public javax.swing.JButton btnCreateUser;
    public javax.swing.JButton btnDeleteEmployee;
    public javax.swing.JButton btnEditEmployee;
    public javax.swing.JButton btnExit;
    private javax.swing.JButton btncuSubmit;
    private javax.swing.JButton btneeSubmit;
    private javax.swing.JComboBox<String> cuAccessLevel;
    private javax.swing.JTextField cuEmployeeID;
    private javax.swing.JPasswordField cuPassword;
    private javax.swing.JTextField cuUsername;
    private javax.swing.JLabel culblAccess;
    private javax.swing.JLabel culblEmployeeID;
    private javax.swing.JLabel culblPassword;
    private javax.swing.JLabel culblUsername;
    private javax.swing.JDialog dlgCreateUser;
    private javax.swing.JDialog dlgEditEmployee;
    private javax.swing.JTextField eeCity;
    private javax.swing.JTextField eeEmail;
    private javax.swing.JTextField eeFirstName;
    private javax.swing.JTextField eeLastName;
    private javax.swing.JTextField eePhone;
    private javax.swing.JTextField eeState;
    private javax.swing.JTextField eeStreet;
    private javax.swing.JTextField eeTitle;
    private javax.swing.JTextField eeZip;
    private javax.swing.JLabel eelblCity;
    private javax.swing.JLabel eelblEmail;
    private javax.swing.JLabel eelblFirstName;
    private javax.swing.JLabel eelblLastName;
    private javax.swing.JLabel eelblPhone;
    private javax.swing.JLabel eelblState;
    private javax.swing.JLabel eelblStreet;
    private javax.swing.JLabel eelblTitle;
    private javax.swing.JLabel eelblZip;
    public javax.swing.JTable employeeTable;
    private javax.swing.JScrollPane scrollPaneTable;
    // End of variables declaration//GEN-END:variables
}
