/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.test;

import PoS.PoS;
import PoS.classes.User;
import javax.swing.table.DefaultTableModel;
import javax.swing.ListSelectionModel;
import java.awt.Component;

/**
 *
 * @author Dustin Gritman
 */
public class UserPanel extends javax.swing.JPanel {
    private final PoS pos;
    
    /**
     * Creates new form TestUserPanel
     * @param pos A PoS object from the main program.
     */
    public UserPanel(PoS pos) {
        initComponents();
        this.pos = pos;
        
        userTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        updateUserTableData();
        
        cuAccessLevel.addItem("User");
        cuAccessLevel.addItem("Admin");
        
        euAccessLevel.addItem("User");
        euAccessLevel.addItem("Admin");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgCreateUser = new javax.swing.JDialog();
        culblUsername = new javax.swing.JLabel();
        cuUsername = new javax.swing.JTextField();
        culblPass = new javax.swing.JLabel();
        cuPassword = new javax.swing.JPasswordField();
        culblEmployeeID = new javax.swing.JLabel();
        cuEmployeeID = new javax.swing.JTextField();
        culblAccessLevel = new javax.swing.JLabel();
        cuAccessLevel = new javax.swing.JComboBox<>();
        btncuSubmit = new javax.swing.JButton();
        dlgEditUser = new javax.swing.JDialog();
        eulblUsername = new javax.swing.JLabel();
        euUsername = new javax.swing.JTextField();
        eulblPassword = new javax.swing.JLabel();
        euPassword = new javax.swing.JPasswordField();
        eulblEmployeeID = new javax.swing.JLabel();
        euEmployeeID = new javax.swing.JTextField();
        eulblAccessLevel = new javax.swing.JLabel();
        euAccessLevel = new javax.swing.JComboBox<>();
        btneuSubmit = new javax.swing.JButton();
        scrollPaneTable = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        btnCreateUser = new javax.swing.JButton();
        btnEditUser = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        dlgCreateUser.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgCreateUser.setTitle("Create User");
        dlgCreateUser.setAlwaysOnTop(true);
        dlgCreateUser.setMinimumSize(new java.awt.Dimension(205, 175));
        dlgCreateUser.setName("dlgCreateUser"); // NOI18N
        dlgCreateUser.setResizable(false);
        dlgCreateUser.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                dlgCreateUserWindowClosed(evt);
            }
        });

        culblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        culblUsername.setText("Username");
        culblUsername.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        culblPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        culblPass.setText("Password");
        culblPass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        culblEmployeeID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        culblEmployeeID.setText("Employee ID");

        culblAccessLevel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        culblAccessLevel.setText("Access Level");

        btncuSubmit.setText("Submit");
        btncuSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncuSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgCreateUserLayout = new javax.swing.GroupLayout(dlgCreateUser.getContentPane());
        dlgCreateUser.getContentPane().setLayout(dlgCreateUserLayout);
        dlgCreateUserLayout.setHorizontalGroup(
            dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgCreateUserLayout.createSequentialGroup()
                .addGroup(dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgCreateUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(culblEmployeeID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(cuUsername, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(culblUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cuEmployeeID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(culblPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cuPassword)
                            .addComponent(culblAccessLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cuAccessLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(dlgCreateUserLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btncuSubmit)))
                .addGap(0, 31, Short.MAX_VALUE))
        );
        dlgCreateUserLayout.setVerticalGroup(
            dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgCreateUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(culblUsername)
                    .addComponent(culblPass))
                .addGap(3, 3, 3)
                .addGroup(dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(culblEmployeeID)
                    .addComponent(culblAccessLevel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuAccessLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncuSubmit)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        dlgEditUser.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgEditUser.setTitle("Edit User");
        dlgEditUser.setAlwaysOnTop(true);
        dlgEditUser.setResizable(false);
        dlgEditUser.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                dlgEditUserWindowClosed(evt);
            }
        });

        eulblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eulblUsername.setText("Username");

        eulblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eulblPassword.setText("Password");

        eulblEmployeeID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eulblEmployeeID.setText("EmployeeID");

        eulblAccessLevel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eulblAccessLevel.setText("AccessLevel");

        btneuSubmit.setText("Submit");
        btneuSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneuSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgEditUserLayout = new javax.swing.GroupLayout(dlgEditUser.getContentPane());
        dlgEditUser.getContentPane().setLayout(dlgEditUserLayout);
        dlgEditUserLayout.setHorizontalGroup(
            dlgEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgEditUserLayout.createSequentialGroup()
                .addGroup(dlgEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgEditUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dlgEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eulblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(euUsername)
                            .addComponent(eulblEmployeeID, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(euEmployeeID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dlgEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eulblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eulblAccessLevel, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(euAccessLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(euPassword)))
                    .addGroup(dlgEditUserLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btneuSubmit)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        dlgEditUserLayout.setVerticalGroup(
            dlgEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgEditUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eulblUsername)
                    .addComponent(eulblPassword))
                .addGap(3, 3, 3)
                .addGroup(dlgEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(euUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(euPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eulblEmployeeID)
                    .addComponent(eulblAccessLevel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgEditUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(euAccessLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(euEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btneuSubmit)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User_ID", "Employee_ID", "Username", "Access_Level"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Short.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        userTable.getTableHeader().setReorderingAllowed(false);
        scrollPaneTable.setViewportView(userTable);
        userTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (userTable.getColumnModel().getColumnCount() > 0) {
            userTable.getColumnModel().getColumn(0).setResizable(false);
            userTable.getColumnModel().getColumn(1).setResizable(false);
            userTable.getColumnModel().getColumn(2).setResizable(false);
            userTable.getColumnModel().getColumn(3).setResizable(false);
        }

        btnCreateUser.setText("Create User");
        btnCreateUser.setToolTipText("");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });

        btnEditUser.setText("Edit User");
        btnEditUser.setToolTipText("");
        btnEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditUserActionPerformed(evt);
            }
        });

        btnDeleteUser.setText("Delete User");
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        btnBack.setText("Back");

        btnExit.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateUser, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUserActionPerformed
        int selectedRow = userTable.getSelectedRow();
        if (selectedRow < 0)
            return;
        
        DefaultTableModel model = (DefaultTableModel)userTable.getModel();
        int userid = (int)model.getValueAt(selectedRow, 0);
        int employeeid = (int)model.getValueAt(selectedRow, 1);
        String username = (String)model.getValueAt(selectedRow, 2);
        short accesslevel = (short)model.getValueAt(selectedRow, 3);
        
        euEmployeeID.setText(String.valueOf(employeeid));
        euUsername.setText(username);
        if (accesslevel == PoS.ADMIN_LEVEL)
            euAccessLevel.setSelectedIndex(1);
        else
            euAccessLevel.setSelectedIndex(0);
        
        dlgEditUser.setSize(dlgEditUser.getPreferredSize());
        disableMainPanel();
        dlgEditUser.setVisible(true);
    }//GEN-LAST:event_btnEditUserActionPerformed

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        dlgCreateUser.setSize(dlgCreateUser.getPreferredSize());
        disableMainPanel();
        dlgCreateUser.setVisible(true);
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btncuSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncuSubmitActionPerformed
        int employeeid = Integer.valueOf(cuEmployeeID.getText());
        String username = cuUsername.getText();
        char[] password = cuPassword.getPassword();
        short accesslevel = 1;
        if (cuAccessLevel.getSelectedItem() == "Admin")
            accesslevel = 5;
        
        pos.users.create(employeeid, username, password, accesslevel);
        updateUserTableData();
        dlgCreateUser.dispose();
    }//GEN-LAST:event_btncuSubmitActionPerformed

    private void dlgCreateUserWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlgCreateUserWindowClosed
        cuUsername.setText("");
        cuEmployeeID.setText("");
        cuPassword.setText("");
        cuAccessLevel.setSelectedIndex(0);
        enableMainPanel();
    }//GEN-LAST:event_dlgCreateUserWindowClosed

    private void btneuSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneuSubmitActionPerformed
        int employeeid = Integer.valueOf(cuEmployeeID.getText());
        String username = euUsername.getText();
        char[] password = euPassword.getPassword();
        short accesslevel = 1;
        if (euAccessLevel.getSelectedItem() == "Admin")
            accesslevel = 5;
        
        updateUserTableData();
        dlgEditUser.dispose();
    }//GEN-LAST:event_btneuSubmitActionPerformed

    private void dlgEditUserWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlgEditUserWindowClosed
        euUsername.setText("");
        euEmployeeID.setText("");
        euPassword.setText("");
        euAccessLevel.setSelectedIndex(0);
        enableMainPanel();
    }//GEN-LAST:event_dlgEditUserWindowClosed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        int selectedRow = userTable.getSelectedRow();
        if (selectedRow < 0)
            return;
        
        DefaultTableModel model = (DefaultTableModel)userTable.getModel();
        int userid = (int)model.getValueAt(selectedRow, 0);
        pos.users.remove(userid);
        updateUserTableData();
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void disableMainPanel() {
        Component[] components = getComponents();
        for (Component component : components)
            component.setEnabled(false);
        userTable.setEnabled(false);
    }
    
    private void enableMainPanel() {
        Component[] components = getComponents();
        for (Component component : components)
            component.setEnabled(true);
        userTable.setEnabled(true);
    }
    
    private void updateUserTableData() {
        DefaultTableModel model = (DefaultTableModel)userTable.getModel();
        model.setRowCount(0);
        User[] userList = pos.users.loadAll();
        for (User user : userList)
            model.addRow(new Object[]{user.getID(), user.getEmployeeID()
                    , user.getUsername(), user.getAccessLevel()}
            );
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBack;
    public javax.swing.JButton btnCreateUser;
    public javax.swing.JButton btnDeleteUser;
    public javax.swing.JButton btnEditUser;
    public javax.swing.JButton btnExit;
    private javax.swing.JButton btncuSubmit;
    private javax.swing.JButton btneuSubmit;
    private javax.swing.JComboBox<String> cuAccessLevel;
    private javax.swing.JTextField cuEmployeeID;
    private javax.swing.JPasswordField cuPassword;
    private javax.swing.JTextField cuUsername;
    private javax.swing.JLabel culblAccessLevel;
    private javax.swing.JLabel culblEmployeeID;
    private javax.swing.JLabel culblPass;
    private javax.swing.JLabel culblUsername;
    private javax.swing.JDialog dlgCreateUser;
    private javax.swing.JDialog dlgEditUser;
    private javax.swing.JComboBox<String> euAccessLevel;
    private javax.swing.JTextField euEmployeeID;
    private javax.swing.JPasswordField euPassword;
    private javax.swing.JTextField euUsername;
    private javax.swing.JLabel eulblAccessLevel;
    private javax.swing.JLabel eulblEmployeeID;
    private javax.swing.JLabel eulblPassword;
    private javax.swing.JLabel eulblUsername;
    private javax.swing.JScrollPane scrollPaneTable;
    public javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
