/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import PoS.PoS;
import PoS.classes.Employee;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arianacarrasq
 */
public class EmployeePage extends javax.swing.JPanel {
    private final PoS pos;
    
    /**
     * Creates new form TestEmployeePanel
     * @param pos A PoS object from the main program.
     */
    public EmployeePage(PoS pos) {
        initComponents();
        this.pos = pos;
        
        employeeTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        updateEmployeeTableData();
        
        cuAccessLevel.addItem("Sales");
        cuAccessLevel.addItem("Inventory");
        cuAccessLevel.addItem("Admin");
        
        UI_Tools.setFocusPainted(this, false);
        UI_Tools.setFocusPainted(dlgEditEmployee, false);
        UI_Tools.setFocusPainted(dlgCreateUser, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgCreateEmployee = new javax.swing.JDialog();
        celblFirstName = new javax.swing.JLabel();
        ceFirstName = new javax.swing.JTextField();
        celblLastName = new javax.swing.JLabel();
        ceLastName = new javax.swing.JTextField();
        celblTitle = new javax.swing.JLabel();
        ceTitle = new javax.swing.JTextField();
        celblPhone = new javax.swing.JLabel();
        cePhone = new javax.swing.JTextField();
        celblState = new javax.swing.JLabel();
        ceState = new javax.swing.JTextField();
        celblCity = new javax.swing.JLabel();
        ceCity = new javax.swing.JTextField();
        celblStreet = new javax.swing.JLabel();
        ceStreet = new javax.swing.JTextField();
        celblZip = new javax.swing.JLabel();
        ceZip = new javax.swing.JTextField();
        btnceSubmit = new javax.swing.JButton();
        celblEmail = new javax.swing.JLabel();
        ceEmail = new javax.swing.JTextField();
        dlgEditEmployee = new javax.swing.JDialog();
        eelblFirstName = new javax.swing.JLabel();
        eeFirstName = new javax.swing.JTextField();
        eelblLastName = new javax.swing.JLabel();
        eeLastName = new javax.swing.JTextField();
        eelblTitle = new javax.swing.JLabel();
        eeTitle = new javax.swing.JTextField();
        eelblPhone = new javax.swing.JLabel();
        eePhone = new javax.swing.JTextField();
        eelblState = new javax.swing.JLabel();
        eeState = new javax.swing.JTextField();
        eelblCity = new javax.swing.JLabel();
        eeCity = new javax.swing.JTextField();
        eelblStreet = new javax.swing.JLabel();
        eeStreet = new javax.swing.JTextField();
        eelblZip = new javax.swing.JLabel();
        eeZip = new javax.swing.JTextField();
        btneeSubmit = new javax.swing.JButton();
        eelblEmail = new javax.swing.JLabel();
        eeEmail = new javax.swing.JTextField();
        dlgCreateUser = new javax.swing.JDialog();
        culblUsername = new javax.swing.JLabel();
        cuUsername = new javax.swing.JTextField();
        culblPassword = new javax.swing.JLabel();
        cuPassword = new javax.swing.JPasswordField();
        culblEmployeeID = new javax.swing.JLabel();
        cuEmployeeID = new javax.swing.JTextField();
        culblAccess = new javax.swing.JLabel();
        cuAccessLevel = new javax.swing.JComboBox<>();
        btncuSubmit = new javax.swing.JButton();
        scrollPaneTable = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        btnCreateEmployee = new javax.swing.JButton();
        btnEditEmployee = new javax.swing.JButton();
        btnDeleteEmployee = new javax.swing.JButton();
        btnCreateUser = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        dlgCreateEmployee.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgCreateEmployee.setTitle("Create Employee");
        dlgCreateEmployee.setAlwaysOnTop(true);
        dlgCreateEmployee.setResizable(false);
        dlgCreateEmployee.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                dlgCreateEmployeeWindowClosed(evt);
            }
        });

        celblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        celblFirstName.setText("First Name");

        celblLastName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        celblLastName.setText("Last Name");

        celblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        celblTitle.setText("Title");

        celblPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        celblPhone.setText("Phone");

        celblState.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        celblState.setText("State");

        celblCity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        celblCity.setText("City");

        celblStreet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        celblStreet.setText("Street");

        celblZip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        celblZip.setText("Zip");

        btnceSubmit.setText("Submit");
        btnceSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnceSubmitActionPerformed(evt);
            }
        });

        celblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        celblEmail.setText("Email");

        javax.swing.GroupLayout dlgCreateEmployeeLayout = new javax.swing.GroupLayout(dlgCreateEmployee.getContentPane());
        dlgCreateEmployee.getContentPane().setLayout(dlgCreateEmployeeLayout);
        dlgCreateEmployeeLayout.setHorizontalGroup(
            dlgCreateEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgCreateEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgCreateEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnceSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dlgCreateEmployeeLayout.createSequentialGroup()
                        .addGroup(dlgCreateEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ceFirstName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(celblFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(celblStreet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ceStreet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dlgCreateEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dlgCreateEmployeeLayout.createSequentialGroup()
                                .addComponent(celblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(celblState, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(celblZip, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dlgCreateEmployeeLayout.createSequentialGroup()
                                .addComponent(ceLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ceTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ceEmail))
                            .addGroup(dlgCreateEmployeeLayout.createSequentialGroup()
                                .addComponent(celblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(celblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(celblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(celblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dlgCreateEmployeeLayout.createSequentialGroup()
                                .addComponent(ceCity, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ceState, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ceZip, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgCreateEmployeeLayout.setVerticalGroup(
            dlgCreateEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgCreateEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgCreateEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(celblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dlgCreateEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(celblFirstName)
                        .addComponent(celblLastName)
                        .addComponent(celblPhone)
                        .addComponent(celblEmail)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgCreateEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ceLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ceFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ceTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ceEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgCreateEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(celblState)
                    .addGroup(dlgCreateEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(celblCity)
                        .addComponent(celblStreet)
                        .addComponent(celblZip)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgCreateEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ceCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ceStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ceZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ceState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnceSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dlgEditEmployee.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgEditEmployee.setTitle("Edit Employee");
        dlgEditEmployee.setAlwaysOnTop(true);
        dlgEditEmployee.setResizable(false);
        dlgEditEmployee.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                dlgEditEmployeeWindowClosed(evt);
            }
        });

        eelblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eelblFirstName.setText("First Name");

        eelblLastName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eelblLastName.setText("Last Name");

        eelblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eelblTitle.setText("Title");

        eelblPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eelblPhone.setText("Phone");

        eelblState.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eelblState.setText("State");

        eelblCity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eelblCity.setText("City");

        eelblStreet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eelblStreet.setText("Street");

        eelblZip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eelblZip.setText("Zip");

        btneeSubmit.setText("Submit");
        btneeSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneeSubmitActionPerformed(evt);
            }
        });

        eelblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eelblEmail.setText("Email");

        javax.swing.GroupLayout dlgEditEmployeeLayout = new javax.swing.GroupLayout(dlgEditEmployee.getContentPane());
        dlgEditEmployee.getContentPane().setLayout(dlgEditEmployeeLayout);
        dlgEditEmployeeLayout.setHorizontalGroup(
            dlgEditEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgEditEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgEditEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btneeSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dlgEditEmployeeLayout.createSequentialGroup()
                        .addGroup(dlgEditEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eeFirstName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eelblFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(eelblStreet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eeStreet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dlgEditEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dlgEditEmployeeLayout.createSequentialGroup()
                                .addComponent(eelblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eelblState, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eelblZip, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dlgEditEmployeeLayout.createSequentialGroup()
                                .addComponent(eeLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eeEmail))
                            .addGroup(dlgEditEmployeeLayout.createSequentialGroup()
                                .addComponent(eelblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eelblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eelblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eelblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dlgEditEmployeeLayout.createSequentialGroup()
                                .addComponent(eeCity, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eeState, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eeZip, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgEditEmployeeLayout.setVerticalGroup(
            dlgEditEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgEditEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgEditEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eelblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dlgEditEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eelblFirstName)
                        .addComponent(eelblLastName)
                        .addComponent(eelblPhone)
                        .addComponent(eelblEmail)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgEditEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eeLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eeFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlgEditEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eelblState)
                    .addGroup(dlgEditEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eelblCity)
                        .addComponent(eelblStreet)
                        .addComponent(eelblZip)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgEditEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eeCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eeStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eeZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eeState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btneeSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dlgCreateUser.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgCreateUser.setTitle("Create User");
        dlgCreateUser.setAlwaysOnTop(true);
        dlgCreateUser.setMinimumSize(new java.awt.Dimension(205, 175));
        dlgCreateUser.setName("dlgCreateUser"); // NOI18N
        dlgCreateUser.setResizable(false);
        dlgCreateUser.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                dlgCreateUserWindowClosed(evt);
            }
        });

        culblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        culblUsername.setText("Username");
        culblUsername.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        culblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        culblPassword.setText("Password");
        culblPassword.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        culblEmployeeID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        culblEmployeeID.setText("Employee ID");

        culblAccess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        culblAccess.setText("Access Level");

        btncuSubmit.setText("Submit");
        btncuSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncuSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgCreateUserLayout = new javax.swing.GroupLayout(dlgCreateUser.getContentPane());
        dlgCreateUser.getContentPane().setLayout(dlgCreateUserLayout);
        dlgCreateUserLayout.setHorizontalGroup(
            dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgCreateUserLayout.createSequentialGroup()
                .addGroup(dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgCreateUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dlgCreateUserLayout.createSequentialGroup()
                                .addComponent(culblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cuEmployeeID)
                            .addComponent(culblEmployeeID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cuUsername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cuPassword)
                            .addComponent(culblAccess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(culblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cuAccessLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(dlgCreateUserLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btncuSubmit)))
                .addContainerGap())
        );
        dlgCreateUserLayout.setVerticalGroup(
            dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgCreateUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(culblUsername)
                    .addComponent(culblPassword))
                .addGap(3, 3, 3)
                .addGroup(dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(culblEmployeeID)
                    .addComponent(culblAccess))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlgCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuAccessLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncuSubmit))
        );

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employees", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N

        employeeTable.setAutoCreateRowSorter(true);
        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "First Name", "Last Name", "Title", "Phone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employeeTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        employeeTable.getTableHeader().setReorderingAllowed(false);
        scrollPaneTable.setViewportView(employeeTable);
        if (employeeTable.getColumnModel().getColumnCount() > 0) {
            employeeTable.getColumnModel().getColumn(0).setMinWidth(100);
            employeeTable.getColumnModel().getColumn(0).setMaxWidth(150);
            employeeTable.getColumnModel().getColumn(4).setMinWidth(75);
            employeeTable.getColumnModel().getColumn(4).setMaxWidth(125);
        }

        btnCreateEmployee.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        btnCreateEmployee.setForeground(new java.awt.Color(250, 163, 111));
        btnCreateEmployee.setText("Create Employee");
        btnCreateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEmployeeActionPerformed(evt);
            }
        });

        btnEditEmployee.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        btnEditEmployee.setForeground(new java.awt.Color(250, 163, 111));
        btnEditEmployee.setText("Edit Employee");
        btnEditEmployee.setToolTipText("");
        btnEditEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditEmployeeActionPerformed(evt);
            }
        });

        btnDeleteEmployee.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        btnDeleteEmployee.setForeground(new java.awt.Color(250, 163, 111));
        btnDeleteEmployee.setText("Delete Employee");
        btnDeleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEmployeeActionPerformed(evt);
            }
        });

        btnCreateUser.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        btnCreateUser.setForeground(new java.awt.Color(250, 163, 111));
        btnCreateUser.setText("Create User");
        btnCreateUser.setToolTipText("");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(250, 163, 111));
        btnBack.setText("Back");

        btnExit.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        btnExit.setForeground(new java.awt.Color(250, 163, 111));
        btnExit.setText("Exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBack, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateEmployee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteEmployee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditEmployee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnCreateEmployee)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditEmployeeActionPerformed
        int selectedRow = employeeTable.getSelectedRow();
        if (selectedRow < 0)
            return;
        
        int employeeid = (int)employeeTable.getModel().getValueAt(
                employeeTable.convertRowIndexToModel(selectedRow), 0);
        Employee employee = pos.employees.load(employeeid);
        
        eeFirstName.setText(employee.getFirstName());
        eeLastName.setText(employee.getLastName());
        eeTitle.setText(employee.getTitle());
        eePhone.setText(employee.getPhone());
        eeEmail.setText(employee.getEmail());
        eeStreet.setText(employee.getStreet());
        eeCity.setText(employee.getCity());
        eeState.setText(employee.getState());
        eeZip.setText("" + employee.getZipcode());
        
        UI_Tools.fixWindow(dlgEditEmployee);
        dlgEditEmployee.setVisible(true);
        disableMainPanel();
    }//GEN-LAST:event_btnEditEmployeeActionPerformed

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        int selectedRow = employeeTable.getSelectedRow();
        if (selectedRow < 0)
            return;
        
        int employeeid = (int)employeeTable.getModel().getValueAt(
                employeeTable.convertRowIndexToModel(selectedRow), 0);
        cuEmployeeID.setText(String.valueOf(employeeid));
        
        UI_Tools.fixWindow(dlgCreateUser);
        dlgCreateUser.setVisible(true);
        disableMainPanel();
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btncuSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncuSubmitActionPerformed
        int employeeid = Integer.valueOf(cuEmployeeID.getText());
        String username = cuUsername.getText();
        char[] password = cuPassword.getPassword();
        short accesslevel = 0;
        if (cuAccessLevel.getSelectedItem() == "Sales")
            accesslevel = PoS.SALES_LEVEL;
        else if (cuAccessLevel.getSelectedItem() == "Inventory")
            accesslevel = PoS.INVENTORY_LEVEL;
        else if (cuAccessLevel.getSelectedItem() == "Admin")
            accesslevel = PoS.ADMIN_LEVEL;
        
        pos.users.create(employeeid, username, password, accesslevel);
        dlgCreateUser.dispose();
        updateEmployeeTableData();
    }//GEN-LAST:event_btncuSubmitActionPerformed

    private void dlgCreateUserWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlgCreateUserWindowClosed
        cuUsername.setText("");
        cuEmployeeID.setText("");
        cuPassword.setText("");
        cuAccessLevel.setSelectedIndex(0);
        enableMainPanel();
    }//GEN-LAST:event_dlgCreateUserWindowClosed

    private void btneeSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneeSubmitActionPerformed
        int selectedRow = employeeTable.getSelectedRow();
        if (selectedRow < 0)
            return;
        
        int employeeid = (int) employeeTable.getModel().getValueAt(
                employeeTable.convertRowIndexToModel(selectedRow), 0);
        String firstName = eeFirstName.getText();
        String lastName = eeLastName.getText();
        String title = eeTitle.getText();
        String phone = eePhone.getText();
        String email = eeEmail.getText();
        String street = eeStreet.getText();
        String city = eeCity.getText();
        String state = eeState.getText();
        int zip = Integer.valueOf(eeZip.getText());
        
        pos.employees.update(employeeid, firstName, lastName, title, phone, email, street, city, state, zip);
        updateEmployeeTableData();
        dlgEditEmployee.dispose();
    }//GEN-LAST:event_btneeSubmitActionPerformed

    private void dlgEditEmployeeWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlgEditEmployeeWindowClosed
        eeFirstName.setText("");
        eeLastName.setText("");
        eeTitle.setText("");
        eePhone.setText("");
        eeEmail.setText("");
        eeStreet.setText("");
        eeCity.setText("");
        eeState.setText("");
        eeZip.setText("");
        
        enableMainPanel();
    }//GEN-LAST:event_dlgEditEmployeeWindowClosed

    private void btnDeleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEmployeeActionPerformed
        int selectedRow = employeeTable.getSelectedRow();
        if (selectedRow < 0)
            return;
        
        int employeeid = (int)employeeTable.getModel().getValueAt(
                employeeTable.convertRowIndexToModel(selectedRow), 0);
        
        pos.employees.remove(employeeid);
        updateEmployeeTableData();
    }//GEN-LAST:event_btnDeleteEmployeeActionPerformed

    private void btnCreateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEmployeeActionPerformed
        ceFirstName.setText("");
        ceLastName.setText("");
        ceTitle.setText("");
        cePhone.setText("");
        ceEmail.setText("");
        ceStreet.setText("");
        ceCity.setText("");
        ceState.setText("");
        ceZip.setText("");
        
        UI_Tools.fixWindow(dlgCreateEmployee);
        dlgCreateEmployee.setVisible(true);
        disableMainPanel();
    }//GEN-LAST:event_btnCreateEmployeeActionPerformed

    private void btnceSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnceSubmitActionPerformed
        String firstName = ceFirstName.getText();
        String lastName = ceLastName.getText();
        String title = ceTitle.getText();
        String phone = cePhone.getText();
        String email = ceEmail.getText();
        String street = ceStreet.getText();
        String city = ceCity.getText();
        String state = ceState.getText();
        int zip = Integer.valueOf(ceZip.getText());
        
        pos.employees.create(firstName, lastName, title, phone, email, street, city, state, zip);
        updateEmployeeTableData();
        dlgCreateEmployee.dispose();
    }//GEN-LAST:event_btnceSubmitActionPerformed

    private void dlgCreateEmployeeWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlgCreateEmployeeWindowClosed
        enableMainPanel();
    }//GEN-LAST:event_dlgCreateEmployeeWindowClosed

    private void disableMainPanel() {
        UI_Tools.updatePanelComponents(this, false);
    }
    
    private void enableMainPanel() {
        UI_Tools.updatePanelComponents(this, true);
    }
    
    private void updateEmployeeTableData() {
        DefaultTableModel model = (DefaultTableModel)employeeTable.getModel();
        model.setRowCount(0);
        Employee[] employeeList = pos.employees.loadAll();
        for (Employee employee : employeeList)
            model.addRow(new Object[]{employee.getID(), employee.getFirstName()
                    , employee.getLastName(), employee.getTitle()
                    , employee.getPhone(), employee.getEmail()}
            );
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateEmployee;
    public javax.swing.JButton btnCreateUser;
    public javax.swing.JButton btnDeleteEmployee;
    public javax.swing.JButton btnEditEmployee;
    public javax.swing.JButton btnExit;
    private javax.swing.JButton btnceSubmit;
    private javax.swing.JButton btncuSubmit;
    private javax.swing.JButton btneeSubmit;
    private javax.swing.JTextField ceCity;
    private javax.swing.JTextField ceEmail;
    private javax.swing.JTextField ceFirstName;
    private javax.swing.JTextField ceLastName;
    private javax.swing.JTextField cePhone;
    private javax.swing.JTextField ceState;
    private javax.swing.JTextField ceStreet;
    private javax.swing.JTextField ceTitle;
    private javax.swing.JTextField ceZip;
    private javax.swing.JLabel celblCity;
    private javax.swing.JLabel celblEmail;
    private javax.swing.JLabel celblFirstName;
    private javax.swing.JLabel celblLastName;
    private javax.swing.JLabel celblPhone;
    private javax.swing.JLabel celblState;
    private javax.swing.JLabel celblStreet;
    private javax.swing.JLabel celblTitle;
    private javax.swing.JLabel celblZip;
    private javax.swing.JComboBox<String> cuAccessLevel;
    private javax.swing.JTextField cuEmployeeID;
    private javax.swing.JPasswordField cuPassword;
    private javax.swing.JTextField cuUsername;
    private javax.swing.JLabel culblAccess;
    private javax.swing.JLabel culblEmployeeID;
    private javax.swing.JLabel culblPassword;
    private javax.swing.JLabel culblUsername;
    private javax.swing.JDialog dlgCreateEmployee;
    private javax.swing.JDialog dlgCreateUser;
    private javax.swing.JDialog dlgEditEmployee;
    private javax.swing.JTextField eeCity;
    private javax.swing.JTextField eeEmail;
    private javax.swing.JTextField eeFirstName;
    private javax.swing.JTextField eeLastName;
    private javax.swing.JTextField eePhone;
    private javax.swing.JTextField eeState;
    private javax.swing.JTextField eeStreet;
    private javax.swing.JTextField eeTitle;
    private javax.swing.JTextField eeZip;
    private javax.swing.JLabel eelblCity;
    private javax.swing.JLabel eelblEmail;
    private javax.swing.JLabel eelblFirstName;
    private javax.swing.JLabel eelblLastName;
    private javax.swing.JLabel eelblPhone;
    private javax.swing.JLabel eelblState;
    private javax.swing.JLabel eelblStreet;
    private javax.swing.JLabel eelblTitle;
    private javax.swing.JLabel eelblZip;
    private javax.swing.JTable employeeTable;
    private javax.swing.JScrollPane scrollPaneTable;
    // End of variables declaration//GEN-END:variables
}
