/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import PoS.PoS;
import PoS.classes.InventoryItem;
import java.math.BigDecimal;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arianacarrasq
 */
public class InventoryPage extends javax.swing.JPanel {
    private final PoS pos;
    
    /**
     * Creates new form InventoryPage
     * @param pos The PoS object that created this page.
     */
    public InventoryPage(PoS pos) {
        initComponents();
        this.pos = pos;
        
        if (pos.getAccessLevel() != PoS.ADMIN_LEVEL)
            backBtn.setText("Logout");
        else
            backBtn.setText("Back");
        updateInventoryTableData();
        
        UI_Tools.setFocusPainted(this, false);
        UI_Tools.setFocusPainted(dlgAddInventory, false);
        UI_Tools.setFocusPainted(dlgEditInventory, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgAddInventory = new javax.swing.JDialog();
        modelNamelbl = new javax.swing.JLabel();
        modelNumlbl = new javax.swing.JLabel();
        serialNumlbl = new javax.swing.JLabel();
        currStocklbl = new javax.swing.JLabel();
        listPricelbl = new javax.swing.JLabel();
        msrpLbl = new javax.swing.JLabel();
        manufLbl = new javax.swing.JLabel();
        baseStocklbl = new javax.swing.JLabel();
        modNameField = new javax.swing.JTextField();
        modNumField = new javax.swing.JTextField();
        serialNumField = new javax.swing.JTextField();
        currStockField = new javax.swing.JTextField();
        listPriceField = new javax.swing.JTextField();
        msrpField = new javax.swing.JTextField();
        manufacturerField = new javax.swing.JTextField();
        baseStockField = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        costlbl = new javax.swing.JLabel();
        costField = new javax.swing.JTextField();
        reorderAmtField = new javax.swing.JTextField();
        costlbl2 = new javax.swing.JLabel();
        dlgEditInventory = new javax.swing.JDialog();
        manufLbl1 = new javax.swing.JLabel();
        baseStocklbl1 = new javax.swing.JLabel();
        modNameField1 = new javax.swing.JTextField();
        modNumField1 = new javax.swing.JTextField();
        serialNumField1 = new javax.swing.JTextField();
        modelNamelbl1 = new javax.swing.JLabel();
        currStockField1 = new javax.swing.JTextField();
        modelNumlbl1 = new javax.swing.JLabel();
        listPriceField1 = new javax.swing.JTextField();
        serialNumlbl1 = new javax.swing.JLabel();
        msrpField1 = new javax.swing.JTextField();
        currStocklbl1 = new javax.swing.JLabel();
        manufacturerField1 = new javax.swing.JTextField();
        listPricelbl1 = new javax.swing.JLabel();
        baseStockField1 = new javax.swing.JTextField();
        msrpLbl1 = new javax.swing.JLabel();
        submitBtn1 = new javax.swing.JButton();
        costlbl1 = new javax.swing.JLabel();
        costField1 = new javax.swing.JTextField();
        reOrderAmtlbl1 = new javax.swing.JLabel();
        reOrderAmtField1 = new javax.swing.JTextField();
        dlgAddStock = new javax.swing.JDialog();
        asAmt = new javax.swing.JTextField();
        aslblAmt = new javax.swing.JLabel();
        submitBtnAS = new javax.swing.JButton();
        dlgRemoveStock = new javax.swing.JDialog();
        rsAmt = new javax.swing.JTextField();
        rslblAmt = new javax.swing.JLabel();
        submitBtnRS = new javax.swing.JButton();
        inventoryPanel = new javax.swing.JPanel();
        inventoryScrollPane = new javax.swing.JScrollPane();
        inventoryTable = new javax.swing.JTable();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        addStockBtn = new javax.swing.JButton();
        removeStockBtn = new javax.swing.JButton();
        textField1 = new javax.swing.JTextField();

        dlgAddInventory.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgAddInventory.setTitle("Create Inventory Item");
        dlgAddInventory.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                dlgAddInventoryWindowClosed(evt);
            }
        });

        modelNamelbl.setText("Model Name: ");

        modelNumlbl.setText("Model #:");

        serialNumlbl.setText("Serial #:");

        currStocklbl.setText("Current Stock:");

        listPricelbl.setText("List Price:");

        msrpLbl.setText("MSRP:");

        manufLbl.setText("Manufacturer:");

        baseStocklbl.setText("Base Stock:");

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        costlbl.setText("Cost:");

        costlbl2.setText("Re-Order Amt:");

        javax.swing.GroupLayout dlgAddInventoryLayout = new javax.swing.GroupLayout(dlgAddInventory.getContentPane());
        dlgAddInventory.getContentPane().setLayout(dlgAddInventoryLayout);
        dlgAddInventoryLayout.setHorizontalGroup(
            dlgAddInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddInventoryLayout.createSequentialGroup()
                .addGroup(dlgAddInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgAddInventoryLayout.createSequentialGroup()
                        .addGroup(dlgAddInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dlgAddInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(dlgAddInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(dlgAddInventoryLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(modelNumlbl))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgAddInventoryLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(costlbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(dlgAddInventoryLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(dlgAddInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(dlgAddInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(costlbl)
                                            .addComponent(baseStocklbl)
                                            .addComponent(manufLbl)
                                            .addComponent(msrpLbl)
                                            .addComponent(listPricelbl))
                                        .addComponent(currStocklbl, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addComponent(serialNumlbl, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(modelNamelbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dlgAddInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(modNumField)
                            .addComponent(serialNumField)
                            .addComponent(currStockField)
                            .addComponent(listPriceField)
                            .addComponent(msrpField)
                            .addComponent(manufacturerField)
                            .addComponent(baseStockField)
                            .addComponent(costField)
                            .addComponent(reorderAmtField)))
                    .addGroup(dlgAddInventoryLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(submitBtn)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        dlgAddInventoryLayout.setVerticalGroup(
            dlgAddInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddInventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgAddInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelNamelbl)
                    .addComponent(modNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgAddInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelNumlbl)
                    .addComponent(modNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgAddInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialNumlbl)
                    .addComponent(serialNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgAddInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currStocklbl)
                    .addComponent(currStockField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgAddInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listPricelbl)
                    .addComponent(listPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgAddInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(msrpLbl)
                    .addComponent(msrpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgAddInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manufLbl)
                    .addComponent(manufacturerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgAddInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baseStocklbl)
                    .addComponent(baseStockField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgAddInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costlbl))
                .addGap(18, 18, 18)
                .addGroup(dlgAddInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reorderAmtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costlbl2))
                .addGap(5, 5, 5)
                .addComponent(submitBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dlgEditInventory.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgEditInventory.setTitle("Edit Inventory Item");
        dlgEditInventory.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                dlgEditInventoryWindowClosed(evt);
            }
        });

        manufLbl1.setText("Manufacturer:");

        baseStocklbl1.setText("Base Stock:");

        modelNamelbl1.setText("Model Name: ");

        modelNumlbl1.setText("Model #:");

        serialNumlbl1.setText("Serial #:");

        currStocklbl1.setText("Current Stock:");

        listPricelbl1.setText("List Price:");

        msrpLbl1.setText("MSRP:");

        submitBtn1.setText("Submit");
        submitBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtn1ActionPerformed(evt);
            }
        });

        costlbl1.setText("Cost:");

        reOrderAmtlbl1.setText("Re-Order Amount:");

        javax.swing.GroupLayout dlgEditInventoryLayout = new javax.swing.GroupLayout(dlgEditInventory.getContentPane());
        dlgEditInventory.getContentPane().setLayout(dlgEditInventoryLayout);
        dlgEditInventoryLayout.setHorizontalGroup(
            dlgEditInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgEditInventoryLayout.createSequentialGroup()
                .addGroup(dlgEditInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgEditInventoryLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dlgEditInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dlgEditInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(modelNumlbl1)
                                .addComponent(modelNamelbl1)
                                .addComponent(serialNumlbl1)
                                .addComponent(currStocklbl1)
                                .addComponent(listPricelbl1))
                            .addGroup(dlgEditInventoryLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(msrpLbl1))
                            .addGroup(dlgEditInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(baseStocklbl1)
                                .addComponent(manufLbl1))
                            .addComponent(costlbl1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(reOrderAmtlbl1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(dlgEditInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modNameField1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(modNumField1)
                            .addComponent(serialNumField1)
                            .addComponent(currStockField1)
                            .addComponent(listPriceField1)
                            .addComponent(msrpField1)
                            .addComponent(manufacturerField1)
                            .addComponent(baseStockField1)
                            .addComponent(costField1)
                            .addComponent(reOrderAmtField1)))
                    .addGroup(dlgEditInventoryLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(submitBtn1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgEditInventoryLayout.setVerticalGroup(
            dlgEditInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgEditInventoryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dlgEditInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelNamelbl1)
                    .addComponent(modNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgEditInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelNumlbl1)
                    .addComponent(modNumField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgEditInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialNumlbl1)
                    .addComponent(serialNumField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgEditInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currStocklbl1)
                    .addComponent(currStockField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgEditInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listPricelbl1)
                    .addComponent(listPriceField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgEditInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(msrpLbl1)
                    .addComponent(msrpField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgEditInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manufLbl1)
                    .addComponent(manufacturerField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgEditInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baseStocklbl1)
                    .addComponent(baseStockField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgEditInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dlgEditInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reOrderAmtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reOrderAmtlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitBtn1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dlgAddStock.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgAddStock.setTitle("Add Stock");
        dlgAddStock.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                dlgAddStockWindowClosed(evt);
            }
        });

        aslblAmt.setText("Amount:");

        submitBtnAS.setText("Submit");
        submitBtnAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnASActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgAddStockLayout = new javax.swing.GroupLayout(dlgAddStock.getContentPane());
        dlgAddStock.getContentPane().setLayout(dlgAddStockLayout);
        dlgAddStockLayout.setHorizontalGroup(
            dlgAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddStockLayout.createSequentialGroup()
                .addGroup(dlgAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgAddStockLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(aslblAmt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(asAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlgAddStockLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(submitBtnAS)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgAddStockLayout.setVerticalGroup(
            dlgAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAddStockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgAddStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aslblAmt)
                    .addComponent(asAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitBtnAS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dlgRemoveStock.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgRemoveStock.setTitle("Remove Stock");
        dlgRemoveStock.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                dlgRemoveStockWindowClosed(evt);
            }
        });

        rslblAmt.setText("Amount:");

        submitBtnRS.setText("Submit");
        submitBtnRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnRSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgRemoveStockLayout = new javax.swing.GroupLayout(dlgRemoveStock.getContentPane());
        dlgRemoveStock.getContentPane().setLayout(dlgRemoveStockLayout);
        dlgRemoveStockLayout.setHorizontalGroup(
            dlgRemoveStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgRemoveStockLayout.createSequentialGroup()
                .addGroup(dlgRemoveStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgRemoveStockLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(rslblAmt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rsAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlgRemoveStockLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(submitBtnRS)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgRemoveStockLayout.setVerticalGroup(
            dlgRemoveStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgRemoveStockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgRemoveStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rslblAmt)
                    .addComponent(rsAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitBtnRS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inventoryPanel.setBackground(new java.awt.Color(102, 102, 102));
        inventoryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inventory", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        inventoryPanel.setPreferredSize(new java.awt.Dimension(700, 700));

        inventoryTable.setAutoCreateRowSorter(true);
        inventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Model Name", "Model #", "Serial #", "Current Stock", "Cost", "List Price", "MSRP", "Manufacturer", "Base Stock", "Re-Order Amt."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        inventoryTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        inventoryScrollPane.setViewportView(inventoryTable);

        addBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        addBtn.setForeground(new java.awt.Color(0, 0, 255));
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        editBtn.setForeground(new java.awt.Color(0, 0, 255));
        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        removeBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        removeBtn.setForeground(new java.awt.Color(0, 0, 255));
        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 0, 255));
        backBtn.setText("Back");

        exitBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(0, 0, 255));
        exitBtn.setText("Exit");

        addStockBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        addStockBtn.setForeground(new java.awt.Color(0, 0, 255));
        addStockBtn.setText("Add Stock");
        addStockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStockBtnActionPerformed(evt);
            }
        });

        removeStockBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        removeStockBtn.setForeground(new java.awt.Color(0, 0, 255));
        removeStockBtn.setText("Remove Stock");
        removeStockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStockBtnActionPerformed(evt);
            }
        });

        textField1.setEditable(false);
        textField1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        textField1.setForeground(new java.awt.Color(243, 141, 63));
        textField1.setText("Inventory Personnel:");

        javax.swing.GroupLayout inventoryPanelLayout = new javax.swing.GroupLayout(inventoryPanel);
        inventoryPanel.setLayout(inventoryPanelLayout);
        inventoryPanelLayout.setHorizontalGroup(
            inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventoryPanelLayout.createSequentialGroup()
                .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inventoryPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(inventoryPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inventoryPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(removeStockBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(addStockBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
                .addContainerGap())
        );
        inventoryPanelLayout.setVerticalGroup(
            inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inventoryPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(addBtn)
                        .addGap(12, 12, 12)
                        .addComponent(editBtn)
                        .addGap(18, 18, 18)
                        .addComponent(removeBtn)
                        .addGap(18, 18, 18)
                        .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(addStockBtn)
                        .addGap(28, 28, 28)
                        .addComponent(removeStockBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitBtn)
                        .addGap(35, 35, 35))
                    .addGroup(inventoryPanelLayout.createSequentialGroup()
                        .addComponent(inventoryScrollPane)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inventoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inventoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        modNameField.setText("");
        modNumField.setText("");
        serialNumField.setText("");
        currStockField.setText("");
        costField.setText("");
        listPriceField.setText("");
        msrpField.setText("");
        manufacturerField.setText("");
        baseStockField.setText("");
        reorderAmtField.setText("");
        
        UI_Tools.fixWindow(dlgAddInventory);
        dlgAddInventory.setVisible(true);
        disableMainPanel();
    }//GEN-LAST:event_addBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        int selectedRow = inventoryTable.getSelectedRow();
        if (selectedRow < 0)
            return;
        selectedRow = inventoryTable.convertRowIndexToModel(selectedRow);
        
        DefaultTableModel model = (DefaultTableModel)inventoryTable.getModel();
        String modelName = (String)model.getValueAt(selectedRow, 0);
        int modelNumber = (int)model.getValueAt(selectedRow, 1);
        String serialNumber = model.getValueAt(selectedRow, 2).toString();
        int currStock = (int)model.getValueAt(selectedRow, 3);
        BigDecimal cost = BigDecimal.valueOf(Double.valueOf(model.getValueAt(selectedRow, 4).toString()));
        BigDecimal listPrice = BigDecimal.valueOf(Double.valueOf(model.getValueAt(selectedRow, 5).toString()));
        BigDecimal msrp = BigDecimal.valueOf(Double.valueOf(model.getValueAt(selectedRow, 6).toString()));
        String manufacturer = (String)model.getValueAt(selectedRow, 7);
        int baseStock = (int)model.getValueAt(selectedRow, 8);
        int reOrderAmt = (int)model.getValueAt(selectedRow, 9);
        
        modNameField1.setText(modelName);
        modNumField1.setText(String.valueOf(modelNumber));
        serialNumField1.setText(String.valueOf(serialNumber));
        currStockField1.setText(String.valueOf(currStock));
        costField1.setText(String.valueOf(cost));
        listPriceField1.setText(String.valueOf(listPrice));
        msrpField1.setText(String.valueOf(msrp));
        manufacturerField1.setText(manufacturer);
        baseStockField1.setText(String.valueOf(baseStock));
        reOrderAmtField1.setText(String.valueOf(reOrderAmt));
        
        UI_Tools.fixWindow(dlgEditInventory);
        dlgEditInventory.setVisible(true);
        disableMainPanel();
    }//GEN-LAST:event_editBtnActionPerformed
   
    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        int selectedRow = inventoryTable.getSelectedRow();
        if (selectedRow < 0)
            return;
        
        String serial = inventoryTable.getModel().getValueAt(
                inventoryTable.convertRowIndexToModel(selectedRow), 2).toString();
        
        pos.inventory.remove(serial);
        updateInventoryTableData();
    }//GEN-LAST:event_removeBtnActionPerformed

    private void addStockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStockBtnActionPerformed
        int selectedRow = inventoryTable.getSelectedRow();
        if (selectedRow < 0)
            return;
        
        asAmt.setText("");
        
        UI_Tools.fixWindow(dlgAddStock);
        dlgAddStock.setVisible(true);
        disableMainPanel();
    }//GEN-LAST:event_addStockBtnActionPerformed

    private void removeStockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStockBtnActionPerformed
        int selectedRow = inventoryTable.getSelectedRow();
        if (selectedRow < 0)
            return;
        
        rsAmt.setText("");
        
        UI_Tools.fixWindow(dlgRemoveStock);
        dlgRemoveStock.setVisible(true);
        disableMainPanel();
    }//GEN-LAST:event_removeStockBtnActionPerformed

    private void submitBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtn1ActionPerformed
        int selectedRow = inventoryTable.getSelectedRow();
        if (selectedRow < 0)
            return;
        
        selectedRow = inventoryTable.convertRowIndexToModel(selectedRow);
        DefaultTableModel model = (DefaultTableModel)inventoryTable.getModel();
        String modelName = (String)model.getValueAt(selectedRow, 0);
        int modelNumber = (int)model.getValueAt(selectedRow, 1);
        int serialNumber = (int)model.getValueAt(selectedRow, 2);
        int currStock = (int)model.getValueAt(selectedRow, 3);
        double cost = (double)model.getValueAt(selectedRow, 4);
        double listPrice = (double)model.getValueAt(selectedRow, 5);
        double msrp = (double)model.getValueAt(selectedRow, 6);
        String manufacturer = (String)model.getValueAt(selectedRow, 7);
        int baseStock = (int)model.getValueAt(selectedRow, 8);
        int reOrderAmt = (int)model.getValueAt(selectedRow, 9);
        
        modNameField1.getText();
        modNumField1.getText();
        serialNumField1.getText();
        currStockField1.getText();
        costField1.getText();
        listPriceField1.getText();
        msrpField1.getText();
        manufacturerField1.getText();
        baseStockField1.getText();
        reOrderAmtField1.getText();
        
        updateInventoryTableData();
        dlgEditInventory.dispose();
    }//GEN-LAST:event_submitBtn1ActionPerformed
 
    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        String modelName = modNameField.getText();
        int modelNumber = Integer.valueOf(modNumField.getText());
        String serialNumber = serialNumField.getText();
        String description = "";
        String supplierLink = "";
        int curStock = Integer.valueOf(currStockField.getText());
        BigDecimal cost  = BigDecimal.valueOf(Double.valueOf(costField.getText()));
        BigDecimal listPrice = BigDecimal.valueOf(Double.valueOf(listPriceField.getText()));
        BigDecimal msrp = BigDecimal.valueOf(Double.valueOf(msrpField.getText()));
        String manufacturer = manufacturerField.getText();
        int baseStock = Integer.valueOf(baseStockField.getText());
        int reorderAmt = Integer.valueOf(reorderAmtField.getText());
        
        pos.inventory.create(serialNumber, manufacturer, modelNumber, modelName
                , description, supplierLink, cost, listPrice, msrp, curStock, baseStock, reorderAmt);
        
        updateInventoryTableData();
        dlgAddInventory.dispose();
    }//GEN-LAST:event_submitBtnActionPerformed

    private void dlgAddInventoryWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlgAddInventoryWindowClosed
        enableMainPanel();
    }//GEN-LAST:event_dlgAddInventoryWindowClosed

    private void dlgEditInventoryWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlgEditInventoryWindowClosed
        enableMainPanel();
    }//GEN-LAST:event_dlgEditInventoryWindowClosed

    private void dlgAddStockWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlgAddStockWindowClosed
        enableMainPanel();
    }//GEN-LAST:event_dlgAddStockWindowClosed

    private void submitBtnASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnASActionPerformed
        int selectedRow = inventoryTable.getSelectedRow();
        if (selectedRow < 0)
            return;
        
        if (!UI_Tools.isInteger(asAmt.getText()))
            return;
        
        int amount = Integer.valueOf(asAmt.getText());
        String serial = inventoryTable.getModel().getValueAt(
                inventoryTable.convertRowIndexToModel(selectedRow), 2).toString();
        
        pos.inventory.updateStock(serial, amount);
        
        updateInventoryTableData();
        dlgAddStock.dispose();
    }//GEN-LAST:event_submitBtnASActionPerformed

    private void submitBtnRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnRSActionPerformed
        int selectedRow = inventoryTable.getSelectedRow();
        if (selectedRow < 0)
            return;
        
        if (!UI_Tools.isInteger(rsAmt.getText()))
            return;
        
        int amount = Integer.valueOf(rsAmt.getText());
        String serial = inventoryTable.getModel().getValueAt(
                inventoryTable.convertRowIndexToModel(selectedRow), 2).toString();
        
        pos.inventory.updateStock(serial, -amount);
        
        updateInventoryTableData();
        dlgRemoveStock.dispose();
    }//GEN-LAST:event_submitBtnRSActionPerformed

    private void dlgRemoveStockWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dlgRemoveStockWindowClosed
        enableMainPanel();
    }//GEN-LAST:event_dlgRemoveStockWindowClosed
    
    private void disableMainPanel() {
        UI_Tools.updatePanelComponents(this, false);
    }
    
    private void enableMainPanel() {
        UI_Tools.updatePanelComponents(this, true);
    }
    
    private void updateInventoryTableData() {
        DefaultTableModel model = (DefaultTableModel) inventoryTable.getModel();
        
        model.setRowCount(0);
        InventoryItem[] inventoryList = pos.inventory.loadAll();
        for (InventoryItem item : inventoryList)
            model.addRow(new Object[] {
                item.getModelName(), item.getModelNumber()
                , item.getSerialNumber(), item.getStock(), item.getCost()
                , item.getListPrice(), item.getMSRP(), item.getManufacturer()
                , item.getBaseStock(), item.getReorderAmount()
            });
        
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addStockBtn;
    private javax.swing.JTextField asAmt;
    private javax.swing.JLabel aslblAmt;
    public javax.swing.JButton backBtn;
    private javax.swing.JTextField baseStockField;
    private javax.swing.JTextField baseStockField1;
    private javax.swing.JLabel baseStocklbl;
    private javax.swing.JLabel baseStocklbl1;
    private javax.swing.JTextField costField;
    private javax.swing.JTextField costField1;
    private javax.swing.JLabel costlbl;
    private javax.swing.JLabel costlbl1;
    private javax.swing.JLabel costlbl2;
    private javax.swing.JTextField currStockField;
    private javax.swing.JTextField currStockField1;
    private javax.swing.JLabel currStocklbl;
    private javax.swing.JLabel currStocklbl1;
    private javax.swing.JDialog dlgAddInventory;
    private javax.swing.JDialog dlgAddStock;
    private javax.swing.JDialog dlgEditInventory;
    private javax.swing.JDialog dlgRemoveStock;
    private javax.swing.JButton editBtn;
    public javax.swing.JButton exitBtn;
    private javax.swing.JPanel inventoryPanel;
    public javax.swing.JScrollPane inventoryScrollPane;
    private javax.swing.JTable inventoryTable;
    private javax.swing.JTextField listPriceField;
    private javax.swing.JTextField listPriceField1;
    private javax.swing.JLabel listPricelbl;
    private javax.swing.JLabel listPricelbl1;
    private javax.swing.JLabel manufLbl;
    private javax.swing.JLabel manufLbl1;
    private javax.swing.JTextField manufacturerField;
    private javax.swing.JTextField manufacturerField1;
    private javax.swing.JTextField modNameField;
    private javax.swing.JTextField modNameField1;
    private javax.swing.JTextField modNumField;
    private javax.swing.JTextField modNumField1;
    private javax.swing.JLabel modelNamelbl;
    private javax.swing.JLabel modelNamelbl1;
    private javax.swing.JLabel modelNumlbl;
    private javax.swing.JLabel modelNumlbl1;
    private javax.swing.JTextField msrpField;
    private javax.swing.JTextField msrpField1;
    private javax.swing.JLabel msrpLbl;
    private javax.swing.JLabel msrpLbl1;
    private javax.swing.JTextField reOrderAmtField1;
    private javax.swing.JLabel reOrderAmtlbl1;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton removeStockBtn;
    private javax.swing.JTextField reorderAmtField;
    private javax.swing.JTextField rsAmt;
    private javax.swing.JLabel rslblAmt;
    private javax.swing.JTextField serialNumField;
    private javax.swing.JTextField serialNumField1;
    private javax.swing.JLabel serialNumlbl;
    private javax.swing.JLabel serialNumlbl1;
    private javax.swing.JButton submitBtn;
    private javax.swing.JButton submitBtn1;
    private javax.swing.JButton submitBtnAS;
    private javax.swing.JButton submitBtnRS;
    private javax.swing.JTextField textField1;
    // End of variables declaration//GEN-END:variables
}
