/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author aamer
 */
public class LoginScreen extends javax.swing.JPanel {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
        autoFillsActive(false);
        UI_Tools.setFocusPainted(this, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        exitButton = new javax.swing.JToggleButton();
        lblMainImage = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JToggleButton();
        lblBoxImage = new javax.swing.JLabel();
        adminFill = new javax.swing.JRadioButton();
        salesFill = new javax.swing.JRadioButton();
        invFill = new javax.swing.JRadioButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMain.setBackground(new java.awt.Color(131, 214, 222));
        panelMain.setLayout(null);

        exitButton.setBackground(new java.awt.Color(131, 214, 222));
        exitButton.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(0, 51, 255));
        exitButton.setText("X");
        exitButton.setBorderPainted(false);
        exitButton.setContentAreaFilled(false);
        panelMain.add(exitButton);
        exitButton.setBounds(269, 0, 40, 30);

        lblMainImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/login1.jpg"))); // NOI18N
        panelMain.add(lblMainImage);
        lblMainImage.setBounds(18, 33, 274, 269);

        lblTitle.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Log In");
        panelMain.add(lblTitle);
        lblTitle.setBounds(110, 370, 80, 30);

        lblUsername.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        lblUsername.setText("Username:");
        panelMain.add(lblUsername);
        lblUsername.setBounds(40, 400, 80, 30);
        panelMain.add(username);
        username.setBounds(120, 400, 140, 30);

        lblPassword.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        lblPassword.setText("Password:");
        panelMain.add(lblPassword);
        lblPassword.setBounds(40, 440, 80, 30);
        panelMain.add(password);
        password.setBounds(120, 440, 140, 30);

        loginButton.setBackground(new java.awt.Color(255, 255, 255));
        loginButton.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/gobtn_6.png"))); // NOI18N
        loginButton.setBorder(null);
        loginButton.setBorderPainted(false);
        loginButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/goClicked_4.png"))); // NOI18N
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginButtonMouseExited(evt);
            }
        });
        panelMain.add(loginButton);
        loginButton.setBounds(40, 480, 220, 40);

        lblBoxImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBoxImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/loginpanel.jpg"))); // NOI18N
        panelMain.add(lblBoxImage);
        lblBoxImage.setBounds(18, 350, 363, 320);

        adminFill.setText("Admin");
        adminFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminFillActionPerformed(evt);
            }
        });
        panelMain.add(adminFill);
        adminFill.setBounds(20, 320, 80, 28);

        salesFill.setText("Sales");
        salesFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesFillActionPerformed(evt);
            }
        });
        panelMain.add(salesFill);
        salesFill.setBounds(210, 320, 80, 28);

        invFill.setText("Inventory");
        invFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invFillActionPerformed(evt);
            }
        });
        panelMain.add(invFill);
        invFill.setBounds(110, 320, 90, 28);

        add(panelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 560));
    }// </editor-fold>//GEN-END:initComponents
    
    private void autoFillsActive(boolean status) {
        adminFill.setVisible(status);
        salesFill.setVisible(status);
        invFill.setVisible(status);
    }
    
    private void adminFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminFillActionPerformed
        if (adminFill.isSelected()) {
            username.setText("admin");
            password.setText("admin");
        }
        else {
            username.setText("");
            password.setText("");
        }
        salesFill.setSelected(false);
        invFill.setSelected(false);
    }//GEN-LAST:event_adminFillActionPerformed
    
    private void salesFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesFillActionPerformed
        if (salesFill.isSelected()) {
            username.setText("sales");
            password.setText("user");
        }
        else {
            username.setText("");
            password.setText("");
        }
        adminFill.setSelected(false);
        invFill.setSelected(false);
    }//GEN-LAST:event_salesFillActionPerformed

    private void invFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invFillActionPerformed
        if (invFill.isSelected()) {
            username.setText("inventory");
            password.setText("user");
        }
        else {
            username.setText("");
            password.setText("");
        }
        adminFill.setSelected(false);
        salesFill.setSelected(false);
    }//GEN-LAST:event_invFillActionPerformed

    private void loginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseEntered
        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/goButton.png"))); // NOI18N
    }//GEN-LAST:event_loginButtonMouseEntered

    private void loginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseExited
        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/images/gobtn_6.png"))); // NOI18N
    }//GEN-LAST:event_loginButtonMouseExited

    public String getUsername() {
        return username.getText();
    }
    
    public char[] getPassword() {
        return password.getPassword();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adminFill;
    public javax.swing.JToggleButton exitButton;
    private javax.swing.JRadioButton invFill;
    private javax.swing.JLabel lblBoxImage;
    private javax.swing.JLabel lblMainImage;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    public javax.swing.JToggleButton loginButton;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPasswordField password;
    private javax.swing.JRadioButton salesFill;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

}
