/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import PoS.PoS;

/**
 *
 * @author arianacarrasq
 */
public class ReportsPage extends javax.swing.JPanel {
    private final PoS pos;
    
    /**
     * Creates new form ReportsPage
     * @param pos A PoS object from the main program.
     */
    public ReportsPage(PoS pos) {
        initComponents();
        this.pos = pos;
        
        UI_Tools.setFocusPainted(this, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reportsTab = new javax.swing.JTabbedPane();
        monthlyPanel = new javax.swing.JPanel();
        weeklyPanel = new javax.swing.JPanel();
        zPanel = new javax.swing.JPanel();
        yearlyPanel = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N

        reportsTab.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        monthlyPanel.setBackground(new java.awt.Color(250, 163, 111));
        monthlyPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout monthlyPanelLayout = new javax.swing.GroupLayout(monthlyPanel);
        monthlyPanel.setLayout(monthlyPanelLayout);
        monthlyPanelLayout.setHorizontalGroup(
            monthlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );
        monthlyPanelLayout.setVerticalGroup(
            monthlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        reportsTab.addTab("Monthly", monthlyPanel);

        weeklyPanel.setBackground(new java.awt.Color(250, 163, 111));
        weeklyPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout weeklyPanelLayout = new javax.swing.GroupLayout(weeklyPanel);
        weeklyPanel.setLayout(weeklyPanelLayout);
        weeklyPanelLayout.setHorizontalGroup(
            weeklyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );
        weeklyPanelLayout.setVerticalGroup(
            weeklyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        reportsTab.addTab("Weekly", weeklyPanel);

        zPanel.setBackground(new java.awt.Color(250, 163, 111));
        zPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout zPanelLayout = new javax.swing.GroupLayout(zPanel);
        zPanel.setLayout(zPanelLayout);
        zPanelLayout.setHorizontalGroup(
            zPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );
        zPanelLayout.setVerticalGroup(
            zPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        reportsTab.addTab("Z", zPanel);

        yearlyPanel.setBackground(new java.awt.Color(250, 163, 111));
        yearlyPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout yearlyPanelLayout = new javax.swing.GroupLayout(yearlyPanel);
        yearlyPanel.setLayout(yearlyPanelLayout);
        yearlyPanelLayout.setHorizontalGroup(
            yearlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );
        yearlyPanelLayout.setVerticalGroup(
            yearlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        reportsTab.addTab("Yearly", yearlyPanel);

        backBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(250, 163, 111));
        backBtn.setText("Back");
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backBtn))
                    .addComponent(reportsTab))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reportsTab))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton backBtn;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel monthlyPanel;
    public javax.swing.JTabbedPane reportsTab;
    public javax.swing.JPanel weeklyPanel;
    public javax.swing.JPanel yearlyPanel;
    public javax.swing.JPanel zPanel;
    // End of variables declaration//GEN-END:variables
}
